version: 2

before:
  hooks:
    - go mod tidy

builds:
  - id: tsk
    main: ./cmd/tsk
    binary: tsk
    ldflags:
      - -s -w -X github.com/tesserakdev/tsk/internal/version.Version={{.Version}}
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64

archives:
  - id: tsk
    name_template: 'tsk_{{ .Os }}_{{ .Arch }}'
    format_overrides:
      - goos: windows
        formats:
          - zip

sboms:
  - artifacts: archive

checksum:
  name_template: checksums.txt

changelog:
  use: github-native
